/* ============================================================================
   STAR Kidz — Party / Distributor master list (grouped by region)
   Drives the "Party / Distributor" dropdown on the order form.
   To add/remove a distributor: edit the right region's list below and save.

   Exposes:
     window.PARTY_GROUPS -> [ { region, names:[...] }, ... ]   (for the dropdown)
     window.PARTIES      -> flat array of every name            (for search/legacy)
============================================================================ */
window.PARTY_GROUPS = [
  { region: 'Assam & Bihar', names: [
    'DHANANI SHOES PRIVATE LIMITED - GUWAHATI',
    'MYGRAND SHOE STORE PVT LTD - KATIHAR',
    'NICE SHOE STORES - KISHANGANJ',
    'PATLIPUTRA DISTRIBUTORS PVT LTD - PATNA',
    'PRINCE FOOTWEAR - MUZAFFARPUR',
    'S N TRADERS - DARBHANGA'
  ]},
  { region: 'Jharkhand', names: [
    'BIHAR SHOE CENTRE',
    'GENERAL LEATHER - DHANBAD',
    'HAPPY SHOES - GIRIDIH',
    'LAL FOOTWEAR - RANCHI',
    'M.A. FOOTWEAR - CHAS'
  ]},
  { region: 'Tripura', names: [
    'SHIBA SALES AGENCY - AGARTALA'
  ]},
  { region: 'West Bengal', names: [
    'B. LEATHERS ELEGANCE PVT LTD',
    'CENTURY SALES CORPORATION - ASANSOL',
    'ELEGENT ENTERPRISES - KOLKATA',
    'HALF & HALF SHOES PRIVATE LTD - KOLKATA',
    'MILEAGE ACTIVEWEAR PRIVATE LTD. - KOLKATA',
    'RATNA FOOTWEAR - SILIGURI'
  ]},
  { region: 'Delhi', names: [
    'D M TRADING COMPANY - SEELAMPUR',
    'NOVA MARKETING',
    'SACHDEVA ENTERPRISES - SUBHASH NAGAR',
    'DEEPAK FOOTWEARS - NAJAFGARH',
    'TECHNOCART ENTERPRISES - NEW DELHI',
    'VIKAS FOOT WEAR - SHAHDARA'
  ]},
  { region: 'Haryana & Chandigarh', names: [
    'AGGARWAL FOOTWEAR - JIND',
    'BANSAL FOOTWEARS - BALLABGARH',
    'DEEPAK CHAPPAL STORE - KARNAL',
    'GAURAV AGENCIES - GURUGRAM',
    'GUPTA FOOTWEAR STORE - PANIPAT',
    'HARYANA SHOE COMPANY - BHIWANI',
    'JYOTI SHOES & GENERAL MERCHANT - SIRSA',
    'KHALSA ENTERPRISES - AMBALA',
    'NAGPAL SHOE CO. - CHANDIGARH',
    'RAJ FOOTWEAR - AMBALA CITY',
    'S. K. TRADERS - TOHANA',
    'V.L.TRADING CO. - SONIPAT'
  ]},
  { region: 'Himachal Pradesh', names: [
    'MOHAN LAL SONS - SOLAN'
  ]},
  { region: 'Jammu & Kashmir', names: [
    'R.S TRADERS - JAMMU'
  ]},
  { region: 'Punjab', names: [
    'ANEJA FOOTWEARS (AGENCIES) - LUDHIANA',
    'B S ENTERPRISES - HOSHIARPUR',
    'DELHI BOOT HOUSE - BARNALA',
    'DIWAN FOOTWEAR - ROPAR',
    'FRIENDS ENTERPRISES - JALANDHAR',
    'H.S.P FOOTWEAR - AMRITSAR',
    'MUNJAL SHOE CO. - FAZILKA',
    'PAWAN BOOT HOUSE - SANGRUR',
    'PRABHAT SHOE CO. - PATIALA',
    'SHIRI ANAND FOOTWEAR - GURDASPUR'
  ]},
  { region: 'Rajasthan', names: [
    'GANPATI FOOTWEARS - JAIPUR',
    'GOYAL FOOTWEAR - HANUMANGARH',
    'GURU JI FOOTWEAR - SRI GANGANAGAR',
    'HIND SHOES - AJMER',
    'JANTA TRADING COMPANY - KOTA',
    'KESHRI MARKETING - BIKANER',
    'OMKAR FOOTSTEP - JAIPUR',
    'R R AGENCIES - JAIPUR',
    'SHUBH AGENCIES - JODHPUR',
    'VIPUL ENTERPRISES - AJMER'
  ]},
  { region: 'Chhattisgarh', names: [
    'BAJAJ FOOTWEAR - RAIPUR',
    'BOMBAY FOOTWEAR - DURG',
    'LARI FOOTWEAR - KORBA',
    'NITIN FOOTWEAR - RAIPUR',
    'ROYAL SHOES - RAIPUR',
    'SHYAM BOOT HOUSE - SAKTI'
  ]},
  { region: 'Madhya Pradesh', names: [
    'ACTIVE AGENCIES - BHOPAL',
    'ALAM BOOT HOUSE - SAGAR',
    'ASHISH ENTERPRISES - JABALPUR',
    'MANISH SHOE PLAZA - INDORE',
    'NEW JHW FOOT WEAR - INDORE',
    'RAYAL SHOUES - KHANDWA',
    'SHUBHAM FOOTWEAR - BHOPAL'
  ]},
  { region: 'Odisha', names: [
    'AB ENTERPRISES - BHADRAK',
    'AFNAAN BOOT HOUSE - FAKIRABAD',
    'DAMANI FOOTWEAR - CUTTACK',
    'DAMANI STORE - ANGUL',
    'HELLO KIDS SHOES - KHORDHA',
    'HI CHOICE FOOTWEAR - BERHAMPUR',
    'KADAM FOOTWEAR - ROURKELA',
    'NEW BHARAT BOOT HOUSE - KESINGA',
    'NIKHIL ENTERPRISES - SAMBHALPUR',
    'BALAJI SALES - BHUBANESWAR',
    'RAJA FOOTWEAR - DASPALLA',
    'RAJPAL FOOTWEAR - CUTTACK',
    'SHOE XPRESS - BHUBNESHWAR'
  ]},
  { region: 'Andhra Pradesh & Telangana', names: [
    'KAMADHENU FOOTNEEDS - KURNOOL',
    'MAANYA FOOTWEAR - VIJAYWADA',
    'NOBEL ASSOCIATES - HYDERABAD',
    'SNEHLATA ASSOCIATES - VIJAYWADA',
    'VENUS ENTERPRISES - VIJAYAWADA'
  ]},
  { region: 'Goa', names: [
    'VINAYAK TRADING - MARGOA'
  ]},
  { region: 'Karnataka', names: [
    'KALA SHOE CENTRE - DAVANGERE',
    'RAJ TRADING CO. - MANGALORE',
    'SANJAY MARKETING - HUBLI',
    'SHRI PADMAVATI DRESSES - HULAKOTI',
    'T. STANES & COMPANY LIMITED - BANGALORE',
    'T. STANES & COMPANY LIMITED - MANGALORE',
    'UDAYAA MARKETING - BENGALORE'
  ]},
  { region: 'Kerala', names: [
    'BROOKS FOOTWEAR GROUPS - THIRUVANANTHAPU',
    'COLOURS TRADERS - KOTTAYAM',
    'FALCON AGENCIES PVT. LTD. - ERNAKULAM',
    'FOOTWEAR AGENCIES - ERNAKULAM',
    'M.M. VENTURES - KARUNAGAPPALLY',
    'MERINO FOOTWEAR TRADERS - ERNAKULAM',
    'S M ENTERPRISES - THIRUVANATHAPURAM',
    'SPLASH MARKETING - ERNAKULAM',
    'SWAPNA AGENCIES - THRISSUR',
    'Y&K POLYMERS - CALICUT'
  ]},
  { region: 'Tamil Nadu & Puducherry', names: [
    'BARUN FOOT TEX - THANJAVAUR',
    'BEAUTY BAGS - PUDUCHEERY',
    'BHALAJI TRADERS - DINDIGUL',
    'ELITE ENTERPRISES - SALEM',
    'MADRAS SHOE MART - CHENNAI',
    'MORFIK MARKETING - CHENNAI',
    'SAFIYA FOOTWEAR - KANNIYAKUMARI',
    'SARAVANA STORES (TEX)',
    'THE LEGEND NEW SARAVANA STORES - 129',
    'THE LEGEND NEW SARAVANA STORES - 15',
    'THE MADRAS SILKS INDIA PVT LTD - CHENNAI',
    'VIJAY TRADERS - CHENNAI'
  ]},
  { region: 'Gujarat', names: [
    'BOSS ENTERPRISES - NAVAGAM',
    'MANISH INTERNATIONAL MF PVT LTD - AHMEDABAD'
  ]},
  { region: 'Maharashtra', names: [
    'ARADHANA SHOES - ULAHASNAGAR',
    'ASHA AGENCIES - PIMPRI',
    'CHANDAN ENTERPRISES - AHMADNAGAR',
    'G S MARKETING - AURANGABAD',
    'GAURI AGENCIES - PIMPRI',
    'KABIR ENTERPRISES - KOLHAPUR',
    'KAPIL ENTERPRISES - TURBHE',
    'KAPIL SHOES - NAGPUR NEW',
    'KARTIK ENTERPRISES - MUMBAI',
    'MAHALAXMI AGENCY - KOLHAPUR',
    'NAMRATA FOOTWEAR - AMRAVATI',
    'NEW MADNE SHOES CENTRE - NANDED',
    'NEW SAINATH SHOE PALACE - AHMADNAGAR',
    'PATEL FOOTWEAR PRIVATE LIMITED - LATUR',
    'PATEL TRADELINK - PRABHANI',
    'PRAKASH ENTERPRISES - BHIWANDI',
    'RAVIRAJ FOOT WEAR - KOLHAPUR',
    'SANCHI ENTERPRISES - PIMPRI',
    'SOHAM SALES - AMALNER',
    'STAR AGENCIES - BARSHI',
    'SWASTIK ENTERPRISES - AKOLA',
    'WANASKAR SALES - SOLAPUR'
  ]},
  { region: 'Nepal', names: [
    'H.N. TRADERS - (BIKASHPATH - NEPAL)',
    'NEPAL FOOTWARE - BUTWAL - NEPAL',
    'R.R.TRADING - KAPILAVASTU - NEPAL'
  ]},
  { region: 'Uttar Pradesh', names: [
    'ANANYA TRADERS - JHANSI',
    'B.K. TRADERS - AMROHA',
    'BAJAJ SHOE CO. - SAHARANPUR',
    'BALKESHWAR NATH ENTERPRISES - AGRA',
    'BANSAL TRADERS - MEERUT',
    'BROTHERS SHOE COMPANY - MUZAFFARNAGAR',
    'CHARAN SHOBHA - MAHARAJGANJ',
    'CLASSIC FOOTWEAR AGENCY - LUCKNOW',
    'EAGLE FOOTWEARS - LUCKNOW',
    'FANCY SHOE COLLECTION - SHAHGANJ',
    'GROVER TRADER - CHANDAUSI',
    'GUPTA TRADERS - KANPUR',
    'PRABHAT SHOE CO - ALIGARH',
    'QUALITY BOOT HOUSE - GORAKHPUR',
    'SHAMSI TRADERS - BAREILLY',
    'SHIVAY ENTERPRISES - VARANASI',
    'SHREE RADHEY ENTERPRISES - PRAYAGRAJ',
    'SHRI BALAJI SALES - GHAZIABAD',
    'SUPER SHOES - VARANASI',
    'WINTEX FOOTWEAR - VARANASI'
  ]},
  { region: 'Uttarakhand', names: [
    'AGARWAL & COMPANY - RAMNAGAR',
    'BAJAJ SHOE COMPANY - DEHRADUN',
    'DURGA ENTERPRISES - RISHIKESH',
    'HIND SHOE AGENCIES - KASHIPUR',
    'JOSHI AGENCIES - KOTDWAR',
    'MAGIC TRADING CO - HALDWANI',
    'RAB AGENCIES - KASHIPUR',
    'SIDHBALI TRADING COMPANY - KOTDWAR'
  ]}
];

// Flat list (kept for search / backward compatibility)
window.PARTIES = window.PARTY_GROUPS.reduce(function (all, g) { return all.concat(g.names); }, []);
